name: PR Validation

on:
  pull_request:
    branches: [main, master]

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm run lint

      - name: Check TypeScript types
        run: pnpm run typecheck

      - name: Check code formatting
        run: pnpm run format:check

      - name: Run tests
        run: pnpm run test:run

      - name: Build project
        run: pnpm run build